### ISSUE TITLE
Outdated link the NAT PMP specification

### ISSUE THREAD

**Issue by frennkie** [jackpal/go-nat-pmp#9]
In the README you are linking to a draft version: https://tools.ietf.org/html/draft-cheshire-nat-pmp-03

The final version is: https://tools.ietf.org/html/rfc6886

Two questions:
* can/will you fix this? (should I send a PR?)
* does this library implement the draft or the final version (sorry.. I haven't check whether there actually are any differences..)?

**Comment by jackpal** [comment]
The library implements the draft specification, as that was the most current specification at the time the code was written.

I updated the source and documentation links to point to the RFC, and I checked the RFC text against the implementation. The implementation seems to be correct, even though it was written against draft 3 instead of the final RFC.
